#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/usr/sbin/crond


start_service () {
	[ -z "$(ls /etc/crontabs/)" ] && return 1


	mkdir -p /var/spool/cron
	ln -s /etc/crontabs/* /var/spool/cron/ 2>/dev/null

	procd_open_instance
	procd_set_param respawn ${respawn_retry:-0} ${respawn_threshold:60} ${respawn_timeout:-10}
	procd_set_param command "$PROG" -S -f -c /var/spool/cron -l "${loglevel:-10}"
	procd_close_instance
}
