#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz

	# set leds to normal state
	. /etc/diag.sh
	set_state done
	
	#zvlastni skripty, ktere se maji spoustet az po kompletnim startu routeru
	#provisioning atd.
	[ -f /etc/lastboot ] && sh /etc/lastboot
}
